# This is a sample build configuration for all languages.
# Check our guides at https://confluence.atlassian.com/x/5Q4SMw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: docker-image:tag
image: golang

pipelines:
  default:
    - step:
        caches:
          - go
        script:
          - source bitbucket-pipelines-go.sh
          - cd ${IMPORT_PATH}
          - git config --global url."git@bitbucket.org:".insteadOf https://bitbucket.org/
          - go get -x bitbucket.org/linkernetworks/foundation/redis
          - go get -x ./cmd/lnk-auth
          - go get -x github.com/stretchr/testify/assert
          - make test
        services:
          - mongo
definitions:
  services:
    mongo:
      image: mongo
  caches:
    go: /go/src
